### PR TITLE
Build fixes for packaging on Haiku

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Maybe some changes still needed, but this atleast fixes packaging this on Haiku, the new variables should work on other OS's also when using PREFIX=

**Comment by Begasus** [comment]
For the tests I had to disable NPOCO in the source files with adding !defined(__HAIKU__), otherwise it would look for the npoco headers also?

**Comment by MayaPosch** [comment]
Thanks for the PR. I have made a number of changes to the Makefile (partially inspired by your suggestions) that should make it work now. I tested it briefly on R1 B5 and it seems to put the files in the proper locations now.

The enabling of `NPOCO` in the tests was still an artefact from testing with that project, and shouldn't have been left in. My apologies for that.

Feel free to test the current version in the repo and see whether it covers the issues which you encountered.

**Comment by Begasus** [comment]
Thanks, checking something else atm, will come back to this. 👍

**Comment by Begasus** [comment]
Added changes won't work on Haiku, hard coded paths should be left out ...

**Comment by MayaPosch** [comment]
I'm not sure I understand what the issue is. The `install` target is for installing into the `/usr/local/` or equivalent folder. A separate `packaging` target could maybe added if that's necessary for Haiku. 

I have tried to find a simple tutorial for creating Haiku packaging to see what's required, but I'm not quite sure what is required here.

**Comment by Begasus** [comment]
All it takes (imho) is a few variables that work for any OS, running this separate from packaging could be done by just setting/using the variables PREFIX (LIBDIR/INCLUDEDIR if needed) from Terminal.
For packaging in Haiku I can post a link later to show you how I did it (which works fine), for that you need haikuporter/haikuports setup explained here: https://github.com/haikuports/haikuporter?tab=readme-ov-file#quick-start

**Comment by Begasus** [comment]
Closing this one for conflicting files.

**Comment by Begasus** [comment]
My current recipe to package this for Haiku: https://github.com/Begasus/haikuports/commit/467fa400f8e83af4fc55fb63c0bb3f6da362e3a2

**Comment by Begasus** [comment]
For the record, got the three library packages build and got [NymphCast](https://github.com/MayaPosch/NymphCast) to build, just not familiar with the usage/launching (gui?) :)

**Comment by MayaPosch** [comment]
> For the record, got the three library packages build and got [NymphCast](https://github.com/MayaPosch/NymphCast) to build, just not familiar with the usage/launching (gui?) :)

As per the README, NymphCast is launched from the CLI, with a configuration file provided via the -c flag :)

**Pull request closed without merging**
